apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: loadbalancer-svc
  selector:
    app: taSki
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taSki
    template:
      metadata:
        labels:
          app: taSki
      spec:
        containers:
          - name: taSki
            image: taskihub/taski_pvt_repo:taskiweb
            imagePullPolicy: Always